# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-26 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190126_1750'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleupdown',
            unique_together=set([('user', 'article')]),
        ),
    ]
